version: '3.5'
services:
  soap:
    build: .
    hostname: soap
    networks:
      - binotify
    ports:
      - "8082:80"
    volumes:
      - "./keys:/usr/src/binotify-soap/keys"
  soapdb:
    image: mysql:latest
    hostname: soapdb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=soapdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - binotify
    volumes:
      - "./scripts/db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9002:80"
    environment:
      - PMA_HOST=soapdb
      - PMA_PORT=3306
    networks:
      - binotify

networks:
  binotify:
    external: true
